"""30B-A3B S-group (semantic defect) results, as a counterpoint to geometry.

Reads runs/probe/part1_sgroup_30b.jsonl (S1-S6 + negatives, A/B/B'/C, T1) and
writes a table + summary, contrasting with the geometry-threshold finding.
"""
from __future__ import annotations

import json
from pathlib import Path

from slide_examiner.analysis import classify_probe_record

REPO = Path(__file__).resolve().parents[1]
PROBE = REPO / "runs" / "probe" / "part1_sgroup_30b.jsonl"
SUMMARY = REPO / "runs" / "probe" / "part1_sgroup_summary.json"
REPORT = REPO / "reports" / "part1_sgroup_30b.md"

DECK = {"S2_NARRATIVE_ORDER_BREAK", "S3_TERMINOLOGY_INCONSISTENCY", "S5_MISSING_LOGIC_SECTION"}
S = ["S1_TITLE_BODY_MISMATCH", "S4_DENSITY_RULE_VIOLATION", "S6_IMAGE_TEXT_CONTRADICTION",
     "S2_NARRATIVE_ORDER_BREAK", "S3_TERMINOLOGY_INCONSISTENCY", "S5_MISSING_LOGIC_SECTION"]
MODS = ("A", "B", "B_prime", "C")


def main() -> None:
    t1 = [r for r in (classify_probe_record(x) for x in (json.loads(l) for l in PROBE.open())) if r.task == "T1"]

    def rc(d, m):
        sub = [r for r in t1 if r.modality == m and d in r.expected_types]
        return sum(d in r.predicted_types for r in sub), len(sub)

    summary = {"model": "qwen3vl-30b", "subset": "data/part1/manifest_sgroup.jsonl", "by_defect": {}, "groups": {}, "false_positives": {}}
    for d in S:
        summary["by_defect"][d] = {"level": "deck" if d in DECK else "page",
                                   **{m: list(rc(d, m)) for m in MODS}}
    for level in ("page", "deck"):
        ds = [d for d in S if (d in DECK) == (level == "deck")]
        summary["groups"][level] = {}
        for m in MODS:
            tp = sum(rc(d, m)[0] for d in ds); n = sum(rc(d, m)[1] for d in ds)
            summary["groups"][level][m] = {"tp": tp, "n": n, "recall": round(tp / n, 3) if n else None}
    for m in MODS:
        neg = [r for r in t1 if r.modality == m and not r.expected_types]
        summary["false_positives"][m] = [sum(bool(r.predicted_types) for r in neg), len(neg)]
    SUMMARY.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    L = []
    L.append("# Part 1 — S-group (semantic) detection on 30B-A3B\n")
    L.append("Real VLM probe (vLLM, Qwen3-VL-30B-A3B-AWQ) over the S-group subset "
             "(S1-S6 + 40 clean negatives, 104 samples), modalities A/B/B'/C, task T1. "
             "B' captions are generated by the same model describing each rendered image "
             "(`scripts/caption_images.py`). 0% parse failure.\n")
    L.append("## Detection recall (TP/n)\n")
    L.append("| Defect | level | A image | B struct | B' caption | C both |")
    L.append("|---|---|---|---|---|---|")
    for d in S:
        bd = summary["by_defect"][d]
        L.append(f"| {d} | {bd['level']} | {bd['A'][0]}/{bd['A'][1]} | {bd['B'][0]}/{bd['B'][1]} | "
                 f"{bd['B_prime'][0]}/{bd['B_prime'][1]} | {bd['C'][0]}/{bd['C'][1]} |")
    g = summary["groups"]
    L.append("")
    L.append(f"**page-S group**: A {g['page']['A']['tp']}/{g['page']['A']['n']}, B {g['page']['B']['tp']}/{g['page']['B']['n']}, "
             f"B' {g['page']['B_prime']['tp']}/{g['page']['B_prime']['n']}, C {g['page']['C']['tp']}/{g['page']['C']['n']}.")
    L.append(f"**deck-S group**: A {g['deck']['A']['tp']}/{g['deck']['A']['n']}, B {g['deck']['B']['tp']}/{g['deck']['B']['n']}, "
             f"B' {g['deck']['B_prime']['tp']}/{g['deck']['B_prime']['n']}, C {g['deck']['C']['tp']}/{g['deck']['C']['n']}.")
    fp = summary["false_positives"]
    L.append("\nClean-negative false positives: " + ", ".join(f"{m} {fp[m][0]}/{fp[m][1]}" for m in MODS) + ".\n")
    L.append("## Findings — semantics is the examiner's job (mirror image of geometry)\n")
    L.append("- **30B detects the semantic group at 50-100%**, versus ~0 for fine geometry (`reports/part1_geometry_threshold.md`). The examiner's value is the S-group, exactly as the contract intends.")
    L.append("- **S1 title/body mismatch reads straight off the image** (A 8/8 = 100%), and **S5 missing-section** is caught ~88%. These are genuine multimodal reasoning wins, not structure look-ups.")
    L.append("- **For deck-level semantics the natural-language caption oracle (B') is the *strongest* channel** (deck-S B' = 20/24 = 83%, vs C = 11/24). This is the exact opposite of geometry, where B' was a dead channel — it validates the B'-via-VLM-captioning fix: S2 narrative-order is 8/8 from B' (the joined per-page captions expose the shuffled order) and S3 terminology is best from B' too.")
    L.append("- **Stacking page images (C) consistently underperforms** the best single channel for deck semantics (C 11/24 < B' 20/24) — the multi-image deck request, though now wired, distracts the model; the structured/linguistic summary is what carries cross-page reasoning.")
    L.append("- **S6 image-text contradiction is 0 everywhere** because the synthetic corpus has no image elements — the defect is not manifest. A real S6 arm needs image-bearing decks; flagged for the dataset freeze.")
    L.append("- **Mild false positives appear on the image channel** (A 3/40) where geometry had none; B/B'/C stay at 0 FP. 30B is slightly more willing to over-call semantics from pixels.\n")
    L.append("## Implication\n")
    L.append("Part 1's division of labor is now empirically grounded on a 30B model: **G1-G6 -> symbolic linter** (VLM blind), **S1-S6 -> examiner**, with the language/structure channels (B, B') carrying deck-level reasoning better than raw multi-image. The full matrix should weight S-group coverage and the B/B' arms, keep C for page-level, and add image-bearing decks so S6 becomes testable.\n")
    REPORT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"Wrote {SUMMARY}\nWrote {REPORT}")


if __name__ == "__main__":
    main()
